version: "3"

services:

  go:
    build:
      context: ./src
      args:
        GOPATH: /go
        IMPORT_PATH: github.com/okashoi/go-lambda-local
    environment:
      GOPATH: /go

  lambda:
    build: ./sam
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./sam:/var/opt
