AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  MyApp:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/main.handle
      Runtime: go1.x
